# key bindings
bindkey '^O' autosuggest-accept   # autosuggestion
bindkey -M viins 'jk' vi-cmd-mode # vi-mode

# find
alias fd='find . -type d -name'
alias ff='find . -type f -name'

# run-help
unalias run-help 2> /dev/null
autoload run-help
alias help='run-help'

# system
alias h="hostname"
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias pgrep='pgrep -l'
alias sudo='sudo -i'
alias tg-init='tg providers lock -platform=darwin_arm64 -platform=darwin_amd64 -platform=linux_amd64'

# project aliases
alias gha='cd ~/work/repos/gh-actions; pwd'

# command aliases
alias umount='diskutil unmount'
alias todo='ultralist'
alias pg.server='pg_ctl -D /usr/local/var/postgresql@14'
alias psql='psql -P pager=off'
alias tf='cd ~/work/devops/terraform; pwd'
alias tg='terragrunt'
alias tga='echo terragrunt apply; tg apply'
alias tgay='echo terragrunt apply -auto-approve; tg apply -auto-approve'
alias tgd='echo terragrunt destroy; tg destroy'
alias tgp='echo terragrunt plan; tg plan'
alias ans='cd ~/work/devops/Ansible; pwd'
alias gbrc='gbr | sort | grep charlie'
alias docs='cd ~/work/docs; pwd'

# ruby aliases
alias be='bundle exec'
alias br='bin/rails'

if command -v pyenv &> /dev/null; then
  eval "$(pyenv init -)"
fi

# autoload functions
if [[ -d $HOME/.functions ]]; then
  for fn in $(find -L $HOME/.functions -type f); do
    autoload -Uz $(basename $fn)
  done
fi

# ssh init
ssh-init

# use neovim if installed
if type nvim &> /dev/null; then
  alias vim='nvim'
fi
# vim:ft=zsh:
