export EDITOR=nvim
export BC_ENV_ARGS=$HOME/.bcrc
export SHELL=/usr/local/bin/zsh
export LESS=-Ri
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# ruby
export RUBYOPT="-W0"
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=/usr/local/opt/openssl@1.1"

# go
export GOPATH=$HOME/go
export GOROOT=/usr/local/opt/go/libexec
export GOBIN=$GOPATH/bin

# groovy
export GROOVY_HOME=/usr/local/opt/groovy/libexec

# java
export JAVA_HOME=$(/usr/libexec/java_home)

# postgres
export PKG_CONFIG_PATH="/usr/local/opt/postgresql@12/lib/pkgconfig"

# aws
export AWS_PAGER=""
export AWS_PROFILE=intellum

# ansible
export ANSIBLE_VAULT_PASSWORD_FILE=./.vault.pass
export ANSIBLE_REMOTE_USER=intellumadmin
export no_proxy=*

# terraform
export NEW_RELIC_REGION="US"

# gcloud
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

# path
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
PATH=/usr/local/opt/ansible@2.9/bin:$PATH
PATH=/usr/local/opt/postgresql@12/bin:$PATH
PATH=/usr/local/opt/openssl/bin:$PATH
PATH=/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:$PATH
PATH=/usr/local/opt/mongodb-community@4.0/bin:$PATH
PATH=$GOBIN:$PATH
export PATH=$HOME/bin:$PATH

# load function dirs into fpath
if [[ -d $HOME/.functions ]]; then
  for dir in $(find -L $HOME/.functions -type d); do
    fpath=($dir $fpath)
  done
  export fpath
fi

# locals
for file in keys aliases; do
  if [[ -f $HOME/.local/$file ]]; then
    source $HOME/.local/$file
  fi
done

# irb
export IRBRC=~/.irbrc

# zsh syntax highligting
# declare the variable
typeset -A ZSH_HIGHLIGHT_STYLES
# To have paths colored instead of underlined
ZSH_HIGHLIGHT_STYLES[path]='fg=white'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=cyan,bold'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=cyan,bold'
VI_MODE_SET_CURSOR=true

# zsh autoupdate
DISABLE_AUTO_UPDATE=true
# vim:ft=zsh:
