# homebrew
export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
export HOMEBREW_REPOSITORY="/opt/homebrew"
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:"
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}"

# go
export GOPATH=$HOME/go
export GOROOT="/opt/homebrew/opt/go/libexec"
export GOBIN=$GOPATH/bin

# path
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH
PATH=$GOBIN:$PATH
export PATH=$HOME/bin:$PATH

# shell
export EDITOR=nvim
export BC_ENV_ARGS=$HOME/.bcrc
export SHELL=/opt/homebrew/bin/zsh
export LESS=-Ri
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# load function dirs into fpath
if [[ -d $HOME/.functions ]]; then
  for dir in $(find -L $HOME/.functions -type d); do
    fpath=($dir $fpath)
  done
  export fpath
fi

if [[ -f $HOME/.local/keys ]]; then
  source $HOME/.local/keys
fi

# irb
export IRBRC=~/.irbrc

# zsh syntax highligting
# declare the variable
typeset -A ZSH_HIGHLIGHT_STYLES
# To have paths colored instead of underlined
ZSH_HIGHLIGHT_STYLES[path]='fg=white'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=cyan,bold'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=cyan,bold'
VI_MODE_SET_CURSOR=true

# zsh autoupdate
DISABLE_AUTO_UPDATE=true
# vim:ft=zsh:
