export EDITOR=vim
export BC_ENV_ARGS=$HOME/.bcrc
export LESS=-Ri
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# ruby
export RUBYOPT="-W0"
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=/usr/local/opt/openssl@1.1"

# go
export GOPATH=$HOME/go
export GOBIN=/usr/local/go/bin

# groovy
export GROOVY_HOME=/usr/local/opt/groovy/libexec

# java
# export JAVA_HOME=$(/usr/libexec/java_home)

# postgres
export PKG_CONFIG_PATH="/usr/local/opt/postgresql@12/lib/pkgconfig"

# path
# PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
# PATH=$PATH:/usr/local/opt/qt@5.5/bin
# PATH=/usr/local/opt/postgresql@12/bin:$PATH
# PATH=/usr/local/opt/openssl/bin:$PATH
# PATH=/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:$PATH
PATH=$GOBIN:$PATH
PATH=$HOME/bin:$PATH
export PATH=$PATH

# load function dirs into fpath
if [[ -d $HOME/.functions ]]; then
  for dir in $(find -L $HOME/.functions -type d); do
    fpath=($dir $fpath)
  done
  export fpath
fi

# irb
export IRBRC=~/.irbrc

# zsh syntax highligting
# declare the variable
typeset -A ZSH_HIGHLIGHT_STYLES
# To have paths colored instead of underlined
ZSH_HIGHLIGHT_STYLES[path]='fg=white'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=cyan,bold'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=cyan,bold'
VI_MODE_SET_CURSOR=true

# zsh autoupdate
DISABLE_AUTO_UPDATE=true
# vim:ft=zsh:
